apiVersion: kubesphere.io/v1alpha1
name: oauth2-proxy
version: 7.6.3
displayName:
  zh: OAuth2-Proxy 
  en: OAuth2-Proxy 
description:
  zh: 用 OAuth2-Proxy 轻松搞定统一认证，保护你的后端应用！
  en: Easily handle unified authentication with OAuth2-Proxy and protect your backend apps!
category: security
keywords:
  - security
  - oauth2-proxy
  - oauth2
  - authentication
home: https://kubesphere.io
sources:
  - https://github.com/oauth2-proxy/oauth2-proxy
kubeVersion: ">=1.19.0-0"
ksVersion: ">=4.0.0-0"
maintainers:
  - name: KubeSphere
    email: kubesphere@yunify.com
provider:
  zh:
    name: "北京青云科技股份有限公司"
    email: "kubesphere@yunify.com"
    url: "https://kubesphere.io"
  en:
    name: "QingCloud Technologies"
    email: "kubesphere@yunify.com"
    url: "https://kubesphere.io"
icon: ./static/favicon.svg
screenshots:
  - ./static/screenshots/architecture.png
dependencies:
  - name: oauth2-proxy
    tags:
    - extension
  - name: openresty
    tags:
    - extension
    condition: openresty.enabled
installationMode: HostOnly
images:
  - quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
  - docker.io/openresty/openresty:1.21.4.1-0-alpine
docs:
  https://oauth2-proxy.github.io/oauth2-proxy/
