kind: ClusterRole
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'extensions.kubesphere.io'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - 'secrets'
---
kind: Role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'app.k8s.io'
      - 'autoscaling'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - 'networking.k8s.io'
    resources:
      - 'ingresses'
      - 'networkpolicies'
  - verbs:
      - '*'
    apiGroups:
      - 'rbac.authorization.k8s.io'
    resources:
      - 'roles'
      - 'rolebindings'
